import React from "react";
import ProductsDisplay from "@/components/ProductsDisplay";
import Head from "next/head";
const index = () => {
  return (
    <div className=" min-h-full bg-white ">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ProductsDisplay />
    </div>
  );
};

export default index;
